/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ai.Relational.Api;
using Ai.Relational.Model;
using Ai.Relational.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ai.Relational.Test
{
    /// <summary>
    ///  Class for testing CardinalityAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CardinalityActionTests
    {
        // TODO uncomment below to declare an instance variable for CardinalityAction
        //private CardinalityAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CardinalityAction
            //instance = new CardinalityAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CardinalityAction
        /// </summary>
        [Test]
        public void CardinalityActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CardinalityAction
            //Assert.IsInstanceOf(typeof(CardinalityAction), instance);
        }


        /// <summary>
        /// Test the property 'Relname'
        /// </summary>
        [Test]
        public void RelnameTest()
        {
            // TODO unit test for the property 'Relname'
        }

    }

}
