/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ai.Relational.Api;
using Ai.Relational.Model;
using Ai.Relational.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ai.Relational.Test
{
    /// <summary>
    ///  Class for testing ClientProblem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientProblemTests
    {
        // TODO uncomment below to declare an instance variable for ClientProblem
        //private ClientProblem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ClientProblem
            //instance = new ClientProblem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClientProblem
        /// </summary>
        [Test]
        public void ClientProblemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ClientProblem
            //Assert.IsInstanceOf(typeof(ClientProblem), instance);
        }


        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Test]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
        /// <summary>
        /// Test the property 'IsError'
        /// </summary>
        [Test]
        public void IsErrorTest()
        {
            // TODO unit test for the property 'IsError'
        }
        /// <summary>
        /// Test the property 'IsException'
        /// </summary>
        [Test]
        public void IsExceptionTest()
        {
            // TODO unit test for the property 'IsException'
        }
        /// <summary>
        /// Test the property 'Report'
        /// </summary>
        [Test]
        public void ReportTest()
        {
            // TODO unit test for the property 'Report'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

    }

}
