/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ai.Relational.Api;
using Ai.Relational.Model;
using Ai.Relational.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ai.Relational.Test
{
    /// <summary>
    ///  Class for testing CollectProblemsAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollectProblemsActionTests
    {
        // TODO uncomment below to declare an instance variable for CollectProblemsAction
        //private CollectProblemsAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CollectProblemsAction
            //instance = new CollectProblemsAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CollectProblemsAction
        /// </summary>
        [Test]
        public void CollectProblemsActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CollectProblemsAction
            //Assert.IsInstanceOf(typeof(CollectProblemsAction), instance);
        }



    }

}
