/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ai.Relational.Api;
using Ai.Relational.Model;
using Ai.Relational.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ai.Relational.Test
{
    /// <summary>
    ///  Class for testing DBType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DBTypeTests
    {
        // TODO uncomment below to declare an instance variable for DBType
        //private DBType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DBType
            //instance = new DBType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DBType
        /// </summary>
        [Test]
        public void DBTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DBType
            //Assert.IsInstanceOf(typeof(DBType), instance);
        }

        /// <summary>
        /// Test deserialize a WrappedType from type DBType
        /// </summary>
        [Test]
        public void WrappedTypeDeserializeFromDBTypeTest()
        {
            // TODO uncomment below to test deserialize a WrappedType from type DBType
            //Assert.IsInstanceOf(typeof(DBType), JsonConvert.DeserializeObject<DBType>(new WrappedType().ToJson()));
        }
        /// <summary>
        /// Test deserialize a ConstantType from type DBType
        /// </summary>
        [Test]
        public void ConstantTypeDeserializeFromDBTypeTest()
        {
            // TODO uncomment below to test deserialize a ConstantType from type DBType
            //Assert.IsInstanceOf(typeof(DBType), JsonConvert.DeserializeObject<DBType>(new ConstantType().ToJson()));
        }

        /// <summary>
        /// Test the property 'Objtp'
        /// </summary>
        [Test]
        public void ObjtpTest()
        {
            // TODO unit test for the property 'Objtp'
        }

    }

}
