/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ai.Relational.Api;
using Ai.Relational.Model;
using Ai.Relational.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ai.Relational.Test
{
    /// <summary>
    ///  Class for testing LabeledActionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LabeledActionResultTests
    {
        // TODO uncomment below to declare an instance variable for LabeledActionResult
        //private LabeledActionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LabeledActionResult
            //instance = new LabeledActionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LabeledActionResult
        /// </summary>
        [Test]
        public void LabeledActionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" LabeledActionResult
            //Assert.IsInstanceOf(typeof(LabeledActionResult), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'Objtp'
        /// </summary>
        [Test]
        public void ObjtpTest()
        {
            // TODO unit test for the property 'Objtp'
        }

    }

}
