/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ai.Relational.Api;
using Ai.Relational.Model;
using Ai.Relational.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ai.Relational.Test
{
    /// <summary>
    ///  Class for testing LoadDataAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoadDataActionTests
    {
        // TODO uncomment below to declare an instance variable for LoadDataAction
        //private LoadDataAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoadDataAction
            //instance = new LoadDataAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoadDataAction
        /// </summary>
        [Test]
        public void LoadDataActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" LoadDataAction
            //Assert.IsInstanceOf(typeof(LoadDataAction), instance);
        }


        /// <summary>
        /// Test the property 'Rel'
        /// </summary>
        [Test]
        public void RelTest()
        {
            // TODO unit test for the property 'Rel'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
