/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ai.Relational.Api;
using Ai.Relational.Model;
using Ai.Relational.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ai.Relational.Test
{
    /// <summary>
    ///  Class for testing ParseActionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParseActionResultTests
    {
        // TODO uncomment below to declare an instance variable for ParseActionResult
        //private ParseActionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ParseActionResult
            //instance = new ParseActionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ParseActionResult
        /// </summary>
        [Test]
        public void ParseActionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ParseActionResult
            //Assert.IsInstanceOf(typeof(ParseActionResult), instance);
        }


        /// <summary>
        /// Test the property 'Problems'
        /// </summary>
        [Test]
        public void ProblemsTest()
        {
            // TODO unit test for the property 'Problems'
        }

    }

}
