/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ai.Relational.Api;
using Ai.Relational.Model;
using Ai.Relational.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ai.Relational.Test
{
    /// <summary>
    ///  Class for testing QueryAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueryActionTests
    {
        // TODO uncomment below to declare an instance variable for QueryAction
        //private QueryAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QueryAction
            //instance = new QueryAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QueryAction
        /// </summary>
        [Test]
        public void QueryActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" QueryAction
            //Assert.IsInstanceOf(typeof(QueryAction), instance);
        }


        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Inputs'
        /// </summary>
        [Test]
        public void InputsTest()
        {
            // TODO unit test for the property 'Inputs'
        }
        /// <summary>
        /// Test the property 'Persist'
        /// </summary>
        [Test]
        public void PersistTest()
        {
            // TODO unit test for the property 'Persist'
        }
        /// <summary>
        /// Test the property 'Outputs'
        /// </summary>
        [Test]
        public void OutputsTest()
        {
            // TODO unit test for the property 'Outputs'
        }

    }

}
