/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ai.Relational.Api;
using Ai.Relational.Model;
using Ai.Relational.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ai.Relational.Test
{
    /// <summary>
    ///  Class for testing Range
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RangeTests
    {
        // TODO uncomment below to declare an instance variable for Range
        //private Range instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Range
            //instance = new Range();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Range
        /// </summary>
        [Test]
        public void RangeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Range
            //Assert.IsInstanceOf(typeof(Range), instance);
        }


        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Test]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }
        /// <summary>
        /// Test the property 'Area'
        /// </summary>
        [Test]
        public void AreaTest()
        {
            // TODO unit test for the property 'Area'
        }
        /// <summary>
        /// Test the property 'StartByte'
        /// </summary>
        [Test]
        public void StartByteTest()
        {
            // TODO unit test for the property 'StartByte'
        }
        /// <summary>
        /// Test the property 'EndByte'
        /// </summary>
        [Test]
        public void EndByteTest()
        {
            // TODO unit test for the property 'EndByte'
        }
        /// <summary>
        /// Test the property 'Objtp'
        /// </summary>
        [Test]
        public void ObjtpTest()
        {
            // TODO unit test for the property 'Objtp'
        }

    }

}
