/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ai.Relational.Api;
using Ai.Relational.Model;
using Ai.Relational.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ai.Relational.Test
{
    /// <summary>
    ///  Class for testing SetOptionsAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetOptionsActionTests
    {
        // TODO uncomment below to declare an instance variable for SetOptionsAction
        //private SetOptionsAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SetOptionsAction
            //instance = new SetOptionsAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SetOptionsAction
        /// </summary>
        [Test]
        public void SetOptionsActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SetOptionsAction
            //Assert.IsInstanceOf(typeof(SetOptionsAction), instance);
        }


        /// <summary>
        /// Test the property 'Debug'
        /// </summary>
        [Test]
        public void DebugTest()
        {
            // TODO unit test for the property 'Debug'
        }
        /// <summary>
        /// Test the property 'DebugTrace'
        /// </summary>
        [Test]
        public void DebugTraceTest()
        {
            // TODO unit test for the property 'DebugTrace'
        }
        /// <summary>
        /// Test the property 'Broken'
        /// </summary>
        [Test]
        public void BrokenTest()
        {
            // TODO unit test for the property 'Broken'
        }
        /// <summary>
        /// Test the property 'Silent'
        /// </summary>
        [Test]
        public void SilentTest()
        {
            // TODO unit test for the property 'Silent'
        }
        /// <summary>
        /// Test the property 'AbortOnError'
        /// </summary>
        [Test]
        public void AbortOnErrorTest()
        {
            // TODO unit test for the property 'AbortOnError'
        }

    }

}
