/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ai.Relational.Api;
using Ai.Relational.Model;
using Ai.Relational.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ai.Relational.Test
{
    /// <summary>
    ///  Class for testing TransactionResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionResultTests
    {
        // TODO uncomment below to declare an instance variable for TransactionResult
        //private TransactionResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransactionResult
            //instance = new TransactionResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransactionResult
        /// </summary>
        [Test]
        public void TransactionResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransactionResult
            //Assert.IsInstanceOf(typeof(TransactionResult), instance);
        }


        /// <summary>
        /// Test the property 'Output'
        /// </summary>
        [Test]
        public void OutputTest()
        {
            // TODO unit test for the property 'Output'
        }
        /// <summary>
        /// Test the property 'Problems'
        /// </summary>
        [Test]
        public void ProblemsTest()
        {
            // TODO unit test for the property 'Problems'
        }
        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Test]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }
        /// <summary>
        /// Test the property 'Aborted'
        /// </summary>
        [Test]
        public void AbortedTest()
        {
            // TODO unit test for the property 'Aborted'
        }
        /// <summary>
        /// Test the property 'Objtp'
        /// </summary>
        [Test]
        public void ObjtpTest()
        {
            // TODO unit test for the property 'Objtp'
        }

    }

}
