/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Ai.Relational.Client.OpenAPIDateConverter;

namespace Ai.Relational.Model
{
    /// <summary>
    /// CardinalityAction
    /// </summary>
    [DataContract]
    public partial class CardinalityAction : Action,  IEquatable<CardinalityAction>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CardinalityAction" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CardinalityAction() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CardinalityAction" /> class.
        /// </summary>
        /// <param name="relname">relname (default to &quot;&quot;).</param>
        public CardinalityAction(string relname = "", string objtp = "") : base(objtp)
        {
            // use default value if no "relname" provided
            if (relname == null)
            {
                this.Relname = "";
            }
            else
            {
                this.Relname = relname;
            }
        }
        
        /// <summary>
        /// Gets or Sets Relname
        /// </summary>
        [DataMember(Name="relname", EmitDefaultValue=false)]
        public string Relname { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CardinalityAction {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Relname: ").Append(Relname).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CardinalityAction);
        }

        /// <summary>
        /// Returns true if CardinalityAction instances are equal
        /// </summary>
        /// <param name="input">Instance of CardinalityAction to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CardinalityAction input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Relname == input.Relname ||
                    (this.Relname != null &&
                    this.Relname.Equals(input.Relname))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Relname != null)
                    hashCode = hashCode * 59 + this.Relname.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
