/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Ai.Relational.Client.OpenAPIDateConverter;

namespace Ai.Relational.Model
{
    /// <summary>
    /// ConstantType
    /// </summary>
    [DataContract]
    public partial class ConstantType : DBType,  IEquatable<ConstantType>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConstantType" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConstantType() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConstantType" /> class.
        /// </summary>
        /// <param name="constant">constant.</param>
        public ConstantType(AnyValue constant = default(AnyValue), string objtp = "") : base(objtp)
        {
            this.Constant = constant;
        }
        
        /// <summary>
        /// Gets or Sets Constant
        /// </summary>
        [DataMember(Name="_constant", EmitDefaultValue=false)]
        public AnyValue Constant { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConstantType {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Constant: ").Append(Constant).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConstantType);
        }

        /// <summary>
        /// Returns true if ConstantType instances are equal
        /// </summary>
        /// <param name="input">Instance of ConstantType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConstantType input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Constant == input.Constant ||
                    (this.Constant != null &&
                    this.Constant.Equals(input.Constant))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Constant != null)
                    hashCode = hashCode * 59 + this.Constant.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
