/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Ai.Relational.Client.OpenAPIDateConverter;

namespace Ai.Relational.Model
{
    /// <summary>
    /// DictElementRelKeyAnyValue
    /// </summary>
    [DataContract]
    public partial class DictElementRelKeyAnyValue :  IEquatable<DictElementRelKeyAnyValue>, IValidatableObject
    {
        /// <summary>
        /// Defines Objtp
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ObjtpEnum
        {
            /// <summary>
            /// Enum DictElementRelKeyAnyValue for value: DictElement_RelKey_AnyValue
            /// </summary>
            [EnumMember(Value = "DictElement_RelKey_AnyValue")]
            DictElementRelKeyAnyValue = 1

        }

        /// <summary>
        /// Gets or Sets Objtp
        /// </summary>
        [DataMember(Name="objtp", EmitDefaultValue=true)]
        public ObjtpEnum Objtp { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DictElementRelKeyAnyValue" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DictElementRelKeyAnyValue() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DictElementRelKeyAnyValue" /> class.
        /// </summary>
        /// <param name="dictArr">dictArr.</param>
        /// <param name="objtp">objtp (required) (default to ObjtpEnum.DictElementRelKeyAnyValue).</param>
        public DictElementRelKeyAnyValue(List<PairRelKeyAnyValue> dictArr = default(List<PairRelKeyAnyValue>), ObjtpEnum objtp = ObjtpEnum.DictElementRelKeyAnyValue)
        {
            // to ensure "objtp" is required (not null)
            if (objtp == null)
            {
                throw new InvalidDataException("objtp is a required property for DictElementRelKeyAnyValue and cannot be null");
            }
            else
            {
                this.Objtp = objtp;
            }
            
            this.DictArr = dictArr;
        }
        
        /// <summary>
        /// Gets or Sets DictArr
        /// </summary>
        [DataMember(Name="dict_arr", EmitDefaultValue=false)]
        public List<PairRelKeyAnyValue> DictArr { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DictElementRelKeyAnyValue {\n");
            sb.Append("  DictArr: ").Append(DictArr).Append("\n");
            sb.Append("  Objtp: ").Append(Objtp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DictElementRelKeyAnyValue);
        }

        /// <summary>
        /// Returns true if DictElementRelKeyAnyValue instances are equal
        /// </summary>
        /// <param name="input">Instance of DictElementRelKeyAnyValue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DictElementRelKeyAnyValue input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DictArr == input.DictArr ||
                    this.DictArr != null &&
                    input.DictArr != null &&
                    this.DictArr.SequenceEqual(input.DictArr)
                ) && 
                (
                    this.Objtp == input.Objtp ||
                    (this.Objtp != null &&
                    this.Objtp.Equals(input.Objtp))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DictArr != null)
                    hashCode = hashCode * 59 + this.DictArr.GetHashCode();
                if (this.Objtp != null)
                    hashCode = hashCode * 59 + this.Objtp.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
