/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Ai.Relational.Client.OpenAPIDateConverter;

namespace Ai.Relational.Model
{
    /// <summary>
    /// Literal
    /// </summary>
    [DataContract]
    public partial class Literal : SyntaxNode,  IEquatable<Literal>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Literal" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Literal() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Literal" /> class.
        /// </summary>
        /// <param name="value">value (default to &quot;&quot;).</param>
        /// <param name="range">range (required).</param>
        /// <param name="missing">missing (default to false).</param>
        public Literal(string value = "", Range range = default(Range), bool missing = false, string objtp = "") : base(objtp)
        {
            // to ensure "range" is required (not null)
            if (range == null)
            {
                throw new InvalidDataException("range is a required property for Literal and cannot be null");
            }
            else
            {
                this.Range = range;
            }
            
            // use default value if no "value" provided
            if (value == null)
            {
                this.Value = "";
            }
            else
            {
                this.Value = value;
            }
            // use default value if no "missing" provided
            if (missing == null)
            {
                this.Missing = false;
            }
            else
            {
                this.Missing = missing;
            }
        }
        
        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }

        /// <summary>
        /// Gets or Sets Range
        /// </summary>
        [DataMember(Name="range", EmitDefaultValue=true)]
        public Range Range { get; set; }

        /// <summary>
        /// Gets or Sets Missing
        /// </summary>
        [DataMember(Name="missing", EmitDefaultValue=false)]
        public bool Missing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Literal {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("  Missing: ").Append(Missing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Literal);
        }

        /// <summary>
        /// Returns true if Literal instances are equal
        /// </summary>
        /// <param name="input">Instance of Literal to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Literal input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && base.Equals(input) && 
                (
                    this.Range == input.Range ||
                    (this.Range != null &&
                    this.Range.Equals(input.Range))
                ) && base.Equals(input) && 
                (
                    this.Missing == input.Missing ||
                    (this.Missing != null &&
                    this.Missing.Equals(input.Missing))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                if (this.Range != null)
                    hashCode = hashCode * 59 + this.Range.GetHashCode();
                if (this.Missing != null)
                    hashCode = hashCode * 59 + this.Missing.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
