/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Ai.Relational.Client.OpenAPIDateConverter;

namespace Ai.Relational.Model
{
    /// <summary>
    /// RelDict
    /// </summary>
    [DataContract]
    public partial class RelDict :  IEquatable<RelDict>, IValidatableObject
    {
        /// <summary>
        /// Defines Objtp
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ObjtpEnum
        {
            /// <summary>
            /// Enum RelDict for value: RelDict
            /// </summary>
            [EnumMember(Value = "RelDict")]
            RelDict = 1

        }

        /// <summary>
        /// Gets or Sets Objtp
        /// </summary>
        [DataMember(Name="objtp", EmitDefaultValue=true)]
        public ObjtpEnum Objtp { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="RelDict" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RelDict() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RelDict" /> class.
        /// </summary>
        /// <param name="dictElem">dictElem.</param>
        /// <param name="objtp">objtp (required) (default to ObjtpEnum.RelDict).</param>
        public RelDict(DictElementRelKeyAnyValue dictElem = default(DictElementRelKeyAnyValue), ObjtpEnum objtp = ObjtpEnum.RelDict)
        {
            // to ensure "objtp" is required (not null)
            if (objtp == null)
            {
                throw new InvalidDataException("objtp is a required property for RelDict and cannot be null");
            }
            else
            {
                this.Objtp = objtp;
            }
            
            this.DictElem = dictElem;
        }
        
        /// <summary>
        /// Gets or Sets DictElem
        /// </summary>
        [DataMember(Name="dict_elem", EmitDefaultValue=false)]
        public DictElementRelKeyAnyValue DictElem { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RelDict {\n");
            sb.Append("  DictElem: ").Append(DictElem).Append("\n");
            sb.Append("  Objtp: ").Append(Objtp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RelDict);
        }

        /// <summary>
        /// Returns true if RelDict instances are equal
        /// </summary>
        /// <param name="input">Instance of RelDict to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RelDict input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DictElem == input.DictElem ||
                    (this.DictElem != null &&
                    this.DictElem.Equals(input.DictElem))
                ) && 
                (
                    this.Objtp == input.Objtp ||
                    (this.Objtp != null &&
                    this.Objtp.Equals(input.Objtp))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DictElem != null)
                    hashCode = hashCode * 59 + this.DictElem.GetHashCode();
                if (this.Objtp != null)
                    hashCode = hashCode * 59 + this.Objtp.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
