/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.RelationalAI.Client.OpenAPIDateConverter;

namespace Com.RelationalAI.Model
{
    /// <summary>
    /// ModifyWorkspaceAction
    /// </summary>
    [DataContract]
    public partial class ModifyWorkspaceAction : Action,  IEquatable<ModifyWorkspaceAction>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifyWorkspaceAction" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ModifyWorkspaceAction() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifyWorkspaceAction" /> class.
        /// </summary>
        /// <param name="deleteEdb">deleteEdb (default to &quot;&quot;).</param>
        /// <param name="deleteSource">deleteSource.</param>
        /// <param name="enableLibrary">enableLibrary (default to &quot;&quot;).</param>
        public ModifyWorkspaceAction(string deleteEdb = "", List<string> deleteSource = default(List<string>), string enableLibrary = "", string type = "") : base(type)
        {
            // use default value if no "deleteEdb" provided
            if (deleteEdb == null)
            {
                this.DeleteEdb = "";
            }
            else
            {
                this.DeleteEdb = deleteEdb;
            }
            this.DeleteSource = deleteSource;
            // use default value if no "enableLibrary" provided
            if (enableLibrary == null)
            {
                this.EnableLibrary = "";
            }
            else
            {
                this.EnableLibrary = enableLibrary;
            }
        }
        
        /// <summary>
        /// Gets or Sets DeleteEdb
        /// </summary>
        [DataMember(Name="delete_edb", EmitDefaultValue=false)]
        public string DeleteEdb { get; set; }

        /// <summary>
        /// Gets or Sets DeleteSource
        /// </summary>
        [DataMember(Name="delete_source", EmitDefaultValue=false)]
        public List<string> DeleteSource { get; set; }

        /// <summary>
        /// Gets or Sets EnableLibrary
        /// </summary>
        [DataMember(Name="enable_library", EmitDefaultValue=false)]
        public string EnableLibrary { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModifyWorkspaceAction {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  DeleteEdb: ").Append(DeleteEdb).Append("\n");
            sb.Append("  DeleteSource: ").Append(DeleteSource).Append("\n");
            sb.Append("  EnableLibrary: ").Append(EnableLibrary).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModifyWorkspaceAction);
        }

        /// <summary>
        /// Returns true if ModifyWorkspaceAction instances are equal
        /// </summary>
        /// <param name="input">Instance of ModifyWorkspaceAction to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModifyWorkspaceAction input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.DeleteEdb == input.DeleteEdb ||
                    (this.DeleteEdb != null &&
                    this.DeleteEdb.Equals(input.DeleteEdb))
                ) && base.Equals(input) && 
                (
                    this.DeleteSource == input.DeleteSource ||
                    this.DeleteSource != null &&
                    input.DeleteSource != null &&
                    this.DeleteSource.SequenceEqual(input.DeleteSource)
                ) && base.Equals(input) && 
                (
                    this.EnableLibrary == input.EnableLibrary ||
                    (this.EnableLibrary != null &&
                    this.EnableLibrary.Equals(input.EnableLibrary))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.DeleteEdb != null)
                    hashCode = hashCode * 59 + this.DeleteEdb.GetHashCode();
                if (this.DeleteSource != null)
                    hashCode = hashCode * 59 + this.DeleteSource.GetHashCode();
                if (this.EnableLibrary != null)
                    hashCode = hashCode * 59 + this.EnableLibrary.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
