/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.RelationalAI.Client.OpenAPIDateConverter;

namespace Com.RelationalAI.Model
{
    /// <summary>
    /// ParseActionResult
    /// </summary>
    [DataContract]
    public partial class ParseActionResult : ActionResult,  IEquatable<ParseActionResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParseActionResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ParseActionResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ParseActionResult" /> class.
        /// </summary>
        /// <param name="problems">problems.</param>
        public ParseActionResult(List<AbstractProblem> problems = default(List<AbstractProblem>), string type = "") : base(type)
        {
            this.Problems = problems;
        }
        
        /// <summary>
        /// Gets or Sets Problems
        /// </summary>
        [DataMember(Name="problems", EmitDefaultValue=false)]
        public List<AbstractProblem> Problems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ParseActionResult {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Problems: ").Append(Problems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ParseActionResult);
        }

        /// <summary>
        /// Returns true if ParseActionResult instances are equal
        /// </summary>
        /// <param name="input">Instance of ParseActionResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ParseActionResult input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Problems == input.Problems ||
                    this.Problems != null &&
                    input.Problems != null &&
                    this.Problems.SequenceEqual(input.Problems)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Problems != null)
                    hashCode = hashCode * 59 + this.Problems.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
