/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Com.RelationalAI.Client.OpenAPIDateConverter;

namespace Com.RelationalAI.Model
{
    /// <summary>
    /// UndefinedError
    /// </summary>
    [DataContract]
    public partial class UndefinedError : AbstractProblem,  IEquatable<UndefinedError>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UndefinedError" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UndefinedError() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UndefinedError" /> class.
        /// </summary>
        /// <param name="range">range (required).</param>
        /// <param name="var">var (default to &quot;&quot;).</param>
        public UndefinedError(Range range = default(Range), string var = "", string type = "") : base(type)
        {
            // to ensure "range" is required (not null)
            if (range == null)
            {
                throw new InvalidDataException("range is a required property for UndefinedError and cannot be null");
            }
            else
            {
                this.Range = range;
            }
            
            // use default value if no "var" provided
            if (var == null)
            {
                this.Var = "";
            }
            else
            {
                this.Var = var;
            }
        }
        
        /// <summary>
        /// Gets or Sets Range
        /// </summary>
        [DataMember(Name="range", EmitDefaultValue=true)]
        public Range Range { get; set; }

        /// <summary>
        /// Gets or Sets Var
        /// </summary>
        [DataMember(Name="var", EmitDefaultValue=false)]
        public string Var { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UndefinedError {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("  Var: ").Append(Var).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UndefinedError);
        }

        /// <summary>
        /// Returns true if UndefinedError instances are equal
        /// </summary>
        /// <param name="input">Instance of UndefinedError to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UndefinedError input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Range == input.Range ||
                    (this.Range != null &&
                    this.Range.Equals(input.Range))
                ) && base.Equals(input) && 
                (
                    this.Var == input.Var ||
                    (this.Var != null &&
                    this.Var.Equals(input.Var))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Range != null)
                    hashCode = hashCode * 59 + this.Range.GetHashCode();
                if (this.Var != null)
                    hashCode = hashCode * 59 + this.Var.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in base.BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
