/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.RelationalAI.Api;
using Com.RelationalAI.Model;
using Com.RelationalAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.RelationalAI.Test
{
    /// <summary>
    ///  Class for testing Area
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AreaTests
    {
        // TODO uncomment below to declare an instance variable for Area
        //private Area instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Area
            //instance = new Area();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Area
        /// </summary>
        [Test]
        public void AreaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Area
            //Assert.IsInstanceOf(typeof(Area), instance);
        }


        /// <summary>
        /// Test the property 'EndPoint'
        /// </summary>
        [Test]
        public void EndPointTest()
        {
            // TODO unit test for the property 'EndPoint'
        }
        /// <summary>
        /// Test the property 'StartPoint'
        /// </summary>
        [Test]
        public void StartPointTest()
        {
            // TODO unit test for the property 'StartPoint'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
