/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.RelationalAI.Api;
using Com.RelationalAI.Model;
using Com.RelationalAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.RelationalAI.Test
{
    /// <summary>
    ///  Class for testing ConstantType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConstantTypeTests
    {
        // TODO uncomment below to declare an instance variable for ConstantType
        //private ConstantType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConstantType
            //instance = new ConstantType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConstantType
        /// </summary>
        [Test]
        public void ConstantTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ConstantType
            //Assert.IsInstanceOf(typeof(ConstantType), instance);
        }


        /// <summary>
        /// Test the property 'Constant'
        /// </summary>
        [Test]
        public void ConstantTest()
        {
            // TODO unit test for the property 'Constant'
        }

    }

}
