/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.RelationalAI.Api;
using Com.RelationalAI.Model;
using Com.RelationalAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.RelationalAI.Test
{
    /// <summary>
    ///  Class for testing CSVFileSyntax
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CSVFileSyntaxTests
    {
        // TODO uncomment below to declare an instance variable for CSVFileSyntax
        //private CSVFileSyntax instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CSVFileSyntax
            //instance = new CSVFileSyntax();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CSVFileSyntax
        /// </summary>
        [Test]
        public void CSVFileSyntaxInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CSVFileSyntax
            //Assert.IsInstanceOf(typeof(CSVFileSyntax), instance);
        }


        /// <summary>
        /// Test the property 'Datarow'
        /// </summary>
        [Test]
        public void DatarowTest()
        {
            // TODO unit test for the property 'Datarow'
        }
        /// <summary>
        /// Test the property 'Delim'
        /// </summary>
        [Test]
        public void DelimTest()
        {
            // TODO unit test for the property 'Delim'
        }
        /// <summary>
        /// Test the property 'Escapechar'
        /// </summary>
        [Test]
        public void EscapecharTest()
        {
            // TODO unit test for the property 'Escapechar'
        }
        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Test]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'HeaderRow'
        /// </summary>
        [Test]
        public void HeaderRowTest()
        {
            // TODO unit test for the property 'HeaderRow'
        }
        /// <summary>
        /// Test the property 'Ignorerepeated'
        /// </summary>
        [Test]
        public void IgnorerepeatedTest()
        {
            // TODO unit test for the property 'Ignorerepeated'
        }
        /// <summary>
        /// Test the property 'Missingstrings'
        /// </summary>
        [Test]
        public void MissingstringsTest()
        {
            // TODO unit test for the property 'Missingstrings'
        }
        /// <summary>
        /// Test the property 'Normalizenames'
        /// </summary>
        [Test]
        public void NormalizenamesTest()
        {
            // TODO unit test for the property 'Normalizenames'
        }
        /// <summary>
        /// Test the property 'Quotechar'
        /// </summary>
        [Test]
        public void QuotecharTest()
        {
            // TODO unit test for the property 'Quotechar'
        }

    }

}
