/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.RelationalAI.Api;
using Com.RelationalAI.Model;
using Com.RelationalAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.RelationalAI.Test
{
    /// <summary>
    ///  Class for testing FileSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileSchemaTests
    {
        // TODO uncomment below to declare an instance variable for FileSchema
        //private FileSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FileSchema
            //instance = new FileSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FileSchema
        /// </summary>
        [Test]
        public void FileSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FileSchema
            //Assert.IsInstanceOf(typeof(FileSchema), instance);
        }

        /// <summary>
        /// Test deserialize a CSVFileSchema from type FileSchema
        /// </summary>
        [Test]
        public void CSVFileSchemaDeserializeFromFileSchemaTest()
        {
            // TODO uncomment below to test deserialize a CSVFileSchema from type FileSchema
            //Assert.IsInstanceOf(typeof(FileSchema), JsonConvert.DeserializeObject<FileSchema>(new CSVFileSchema().ToJson()));
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
