/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.RelationalAI.Api;
using Com.RelationalAI.Model;
using Com.RelationalAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.RelationalAI.Test
{
    /// <summary>
    ///  Class for testing ModifyWorkspaceAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModifyWorkspaceActionTests
    {
        // TODO uncomment below to declare an instance variable for ModifyWorkspaceAction
        //private ModifyWorkspaceAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModifyWorkspaceAction
            //instance = new ModifyWorkspaceAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModifyWorkspaceAction
        /// </summary>
        [Test]
        public void ModifyWorkspaceActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ModifyWorkspaceAction
            //Assert.IsInstanceOf(typeof(ModifyWorkspaceAction), instance);
        }


        /// <summary>
        /// Test the property 'DeleteEdb'
        /// </summary>
        [Test]
        public void DeleteEdbTest()
        {
            // TODO unit test for the property 'DeleteEdb'
        }
        /// <summary>
        /// Test the property 'DeleteSource'
        /// </summary>
        [Test]
        public void DeleteSourceTest()
        {
            // TODO unit test for the property 'DeleteSource'
        }
        /// <summary>
        /// Test the property 'EnableLibrary'
        /// </summary>
        [Test]
        public void EnableLibraryTest()
        {
            // TODO unit test for the property 'EnableLibrary'
        }

    }

}
