/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.RelationalAI.Api;
using Com.RelationalAI.Model;
using Com.RelationalAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.RelationalAI.Test
{
    /// <summary>
    ///  Class for testing SyntaxNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SyntaxNodeTests
    {
        // TODO uncomment below to declare an instance variable for SyntaxNode
        //private SyntaxNode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SyntaxNode
            //instance = new SyntaxNode();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SyntaxNode
        /// </summary>
        [Test]
        public void SyntaxNodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SyntaxNode
            //Assert.IsInstanceOf(typeof(SyntaxNode), instance);
        }

        /// <summary>
        /// Test deserialize a Token from type SyntaxNode
        /// </summary>
        [Test]
        public void TokenDeserializeFromSyntaxNodeTest()
        {
            // TODO uncomment below to test deserialize a Token from type SyntaxNode
            //Assert.IsInstanceOf(typeof(SyntaxNode), JsonConvert.DeserializeObject<SyntaxNode>(new Token().ToJson()));
        }
        /// <summary>
        /// Test deserialize a Appl from type SyntaxNode
        /// </summary>
        [Test]
        public void ApplDeserializeFromSyntaxNodeTest()
        {
            // TODO uncomment below to test deserialize a Appl from type SyntaxNode
            //Assert.IsInstanceOf(typeof(SyntaxNode), JsonConvert.DeserializeObject<SyntaxNode>(new Appl().ToJson()));
        }
        /// <summary>
        /// Test deserialize a Literal from type SyntaxNode
        /// </summary>
        [Test]
        public void LiteralDeserializeFromSyntaxNodeTest()
        {
            // TODO uncomment below to test deserialize a Literal from type SyntaxNode
            //Assert.IsInstanceOf(typeof(SyntaxNode), JsonConvert.DeserializeObject<SyntaxNode>(new Literal().ToJson()));
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
