/* 
 * Delve Client SDK
 *
 * This is a Client SDK for Delve API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relational.ai
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.RelationalAI.Api;
using Com.RelationalAI.Model;
using Com.RelationalAI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Com.RelationalAI.Test
{
    /// <summary>
    ///  Class for testing UpdateAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateActionTests
    {
        // TODO uncomment below to declare an instance variable for UpdateAction
        //private UpdateAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateAction
            //instance = new UpdateAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateAction
        /// </summary>
        [Test]
        public void UpdateActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UpdateAction
            //Assert.IsInstanceOf(typeof(UpdateAction), instance);
        }


        /// <summary>
        /// Test the property 'Delta'
        /// </summary>
        [Test]
        public void DeltaTest()
        {
            // TODO unit test for the property 'Delta'
        }
        /// <summary>
        /// Test the property 'Rel'
        /// </summary>
        [Test]
        public void RelTest()
        {
            // TODO unit test for the property 'Rel'
        }
        /// <summary>
        /// Test the property 'Updates'
        /// </summary>
        [Test]
        public void UpdatesTest()
        {
            // TODO unit test for the property 'Updates'
        }

    }

}
